export function bountyOpenapi() {
  const id = { in: 'path', name: 'id', required: true, schema: { type: 'string' } };
  const retry = { in: 'header', name: 'Idempotency-Key', required: true, schema: { type: 'string', pattern: '^[A-Za-z0-9._:-]{1,128}$' } };
  const offer = { type: 'object', required: ['schema_version', 'seller_id', 'payout_wallet', 'network', 'currency', 'price_minor', 'sla_minutes', 'capability', 'deliverable'], properties: {
    schema_version: { const: 'seller-offer/v1' }, seller_id: { type: 'string' }, payout_wallet: { type: 'string' }, network: { enum: ['base', 'solana'] }, currency: { const: 'USDC' }, price_minor: { type: 'integer', minimum: 1, description: 'USDC micro-units; poster reward must be 500000–2000000; claimer price must not exceed reward.' }, sla_minutes: { type: 'integer', minimum: 1 }, capability: { type: 'string' }, deliverable: { type: 'object', required: ['description', 'mime_type'], properties: { description: { type: 'string' }, mime_type: { type: 'string' } } },
  } };
  const operation = (summary, schema, isPost = false) => ({ summary, security: [{ bearer: [] }], parameters: isPost ? [retry] : [id, retry], requestBody: { required: true, content: { 'application/json': { schema } } }, responses: Object.fromEntries([[isPost ? '201' : '200', 'Durable {success:true,data:{bounty}}; completion contains signed completion_receipt and settlement.status=not_paid'], ['400', 'Malformed JSON/body/offer/amount/completion or missing idempotency key'], ['401', 'Missing/invalid bearer credential'], ['403', 'Actor lacks authority, self-claim, or preflight denied'], ['404', 'Bounty not found'], ['409', 'State or idempotency conflict'], ['503', 'Seller/preflight unavailable, invalid, expired or mismatched']].map(([code, description]) => [code, { description }])) });
  return { openapi: '3.1.0', info: { title: 'TWZRD bounty coordinator', version: '1.0.0', description: 'Separate authenticated service. Server-side HTTP seller cards; TWZRD preflight before listing and completion payout eligibility. No funds transfer. Pin the verification key independently.' }, components: { securitySchemes: { bearer: { type: 'http', scheme: 'bearer' } } }, paths: {
    '/bounties': { post: operation('Post a gated bounty', { type: 'object', required: ['poster', 'task'], properties: { poster: offer, task: { type: 'object', required: ['description'], properties: { description: { type: 'string', minLength: 1, maxLength: 8000 } } } } }, true) },
    '/bounties/{id}/claim': { post: operation('Claim with HTTP card from stored delivery history', { type: 'object', required: ['claimer'], properties: { claimer: offer } }) },
    '/bounties/{id}/complete': { post: operation('Poster/operator records acceptance and signed artifact digest', { type: 'object', required: ['outcome', 'artifact'], properties: { outcome: { type: 'object', required: ['decision'], properties: { decision: { enum: ['accepted', 'rejected'] } } }, artifact: { type: 'object', required: ['sha256', 'description'], properties: { sha256: { type: 'string', pattern: '^[a-f0-9]{64}$' }, description: { type: 'string', minLength: 1, maxLength: 8000 } } } } }) },
    '/bounties/{id}': { get: { summary: 'Authenticated bounty read', security: [{ bearer: [] }], parameters: [id], responses: { '200': { description: '{success:true,data:{bounty}}' }, '401': { description: 'Unauthorized' }, '404': { description: 'Not found' } } } },
    ...Object.fromEntries(['/bounties-key', '/openapi.json', '/llms.txt', '/skill.md'].map(p => [p, { get: { summary: p === '/bounties-key' ? 'Public Ed25519 verification key and evidence mode' : 'Public service documentation', security: [], responses: { '200': { description: 'Documentation or public key' } } } }])),
  } };
}
